In [ ]:
import torch
from tabulate import tabulate
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
t = torch.tensor([[1,2],[3,4]])
t = torch.tensor(([1,2],[3,4]),dtype=torch.float64)
t = torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
t = torch.tensor([[1,2,3],[4,5,6]])
# index 를 활용해서 특정 위치의 tenstor element 를 출력할 수 있음
t[0,2] # 3
# 슬라이스를 활용하여서 조작도 가능
t[:,0]
# 마스크 배열을 사용함(원 배열과 크기는 같지만 각 요소가 True / False 로 설정되어있음)
t[t>2] # [3,4,5,6]
pd_t = pd.DataFrame([[1,2,3],[4,5,6]]) 
pd_t[pd_t>2] # pandas 는 table 형태 유지함
# index 에 값 설정 
t[0,2] = 100 
t[:,1] = 200 # 일괄 삽입 
t[t<3] = 0 
t 

tensor([[  0, 200, 100],
        [  4, 200,   6]])

In [ ]:
v = torch.tensor([1,2,3])
w = torch.tensor([0,10,20])
m = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
# 브로드캐스트 작동
m + v
x = torch.randn(5,3)
torch.abs(x) # 값들 모두 절댓값 처리
torch.mean(x) # 값들에 대한 평균
torch.mean(x,dim=0) # Axis 에 대한 평균

tensor([0.3394, 0.3160, 0.6365])

In [ ]:
x1 = torch.tensor([[1,2],[3,4]])
x2 = torch.tensor([[10,20,30],[40,50,60]])
# view 를 통해서 차원 조작 가능 
x1.view(1,4)
x1.view(1,-1) # -1 은 가능한대로 transpose

x2.t()
torch.cat([x1,x2],dim=1)

hcm_img_data = torch.rand(100,64,32,3)

In [ ]:
pd_t = pd.DataFrame([[1,2,3],[4,5,6]]) 
pd_t[pd_t>2]

0    1  2
0  NaN  NaN  3
1  4.0  5.0  6

In [ ]:
torch.randn(100,10)
torch.randn(10)